version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./play-gm-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend